# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo/

    steps:
      - checkout

      - run:
          working_directory: ~/repo/src
          command: |
            yarn install

        
      # run tests!
      #- run: yarn run deploy
      # this is a change

      - deploy:
          name: Maybe Deploy
          working_directory: ~/repo/src
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run deployprod
            else
              yarn run deploydev
            fi
            


